export const AUTHSTACK = 'AUTHSTACK';
export const AUTH_LOADING_SCREEN = 'AUTH_LOADING_SCREEN';

export const WELCOME_SCREEN = 'WELCOME_SCREEN';
export const LOGIN_SCREEN = 'LOGIN_SCREEN';
export const REGISTER_SCREEN = 'REGISTER_SCREEN';
export const REFERRAL_SCREEN = 'REFERRAL_SCREEN';
export const OTP_SCREEN = 'OTP_SCREEN';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const RESET_PASSWORD = 'RESET_PASSWORD';
export const NFT_SCREEN1 = 'NFT_SCREEN1';
export const HOME_SCREEN = 'HOME_SCREEN';
export const RENTED_SCREEN = 'RENTED_SCREEN';
export const PURCHASE_SCREEN = 'PURCHASE_SCREEN';
export const SETTING = 'SETTING';
export const RENTED_FLATLIST = 'RENTED_FLATLIST';
export const PURCHASED_FLATLIST = 'PURCHASED_FLATLIST';

export const NFC = 'NFC';
export const PROFILE = 'PROFILE_SCREEN';
export const REFER_EARN = ' REFER_EARN';
export const PROFILE_EDIT = 'EDIT_PROFILE_SCREEN';
export const MY_BALANCE = 'MY_BALANCE';
export const HOME = 'HOME';
export const CONTEST = 'CONTEST';
export const PRACTISE_SCREEN = 'PRACTISE-SCREEN';
export const SELECT_PLAYER = 'SELECT-PLAYER';
export const PLAYER_PREVIEW = 'PLAYER-PREVIEW';
export const MY_CONTEST = 'MY-CONTEST';
export const ALL_CONTEST_LIST = 'ALL-CONTEST-LIST';
export const SELECT_CAPTAIN = 'SELECT-CAPTAIN';
export const LEADERBOARD = 'LEADERBOARD';
export const ADD_MONEY_SCREEN = 'ADD_MONEY_SCREEN';
export const PAYMENT_OPTIONS_SCREEN = 'PAYMENT_OPTIONS_SCREEN';
export const MY_MATCHES = 'MY_MATCHES';
export const PLAY_SCREEN = 'PLAY_SCREEN';


// export const

// BOTTOM TABS
export const BOTTOM_NAVIGATION_STACK = 'BOTTOM_NAVIGATION_STACK';

export const BOTTOM_TAB_HOMESCREEN = 'BOTTOM_TAB_HOMESCREEN';
export const BOTTOM_TAB_MESSAGE_SCREEN = 'BOTTOM_TAB_MESSAGE_SCREEN';
export const BOTTOM_TAB_ADDMORE_SCREEN = 'BOTTOM_TAB_ADDMORE_SCREEN';
export const BOTTOM_TAB_USERPROFILE_SCREEN = 'BOTTOM_TAB_USERPROFILE_SCREEN';
export const BOTTOM_TAB_MENU_SCREEN = 'BOTTOM_TAB_MENU_SCREEN';
export const BOTTOM_TAB_CONTEST_SCREEN = 'BOTTOM_TAB_CONTEST_SCREEN';
export const BOTTOM_TAB_PROFILE_SCREEN = 'BOTTOM_TAB_PROFILE_SCREEN';
export const BOTTOM_TAB_MORE_SCREEN = 'BOTTOM_TAB_MORE_SCREEN';
export const HOME_SCREEN_MAIN = 'HOME_SCREEN_MAIN';
export const CONTEST_SCREEN_MAIN = 'CONTEST_SCREEN_MAIN';
export const PROFILE_SCREEN_MAIN = 'PROFILE_SCREEN_MAIN';
export const MORE_SCREEN_MAIN = 'MORE_SCREEN_MAIN';
export const DEPOSIT_IBAT_SCREEN = 'DEPOSIT_IBAT_SCREEN';
export const DEPOSIT_WITHDRAWAL_SCREEN = 'DEPOSIT_WITHDRAWAL_SCREEN';
export const KYC_SCREEN = 'KYC_SCREEN';
export const VERIFY_EMAIL_SCREEN = 'VERIFY_EMAIL_SCREEN';
export const VERIFY_EMAIL_OTP_SCREEN = 'VERIFY_EMAIL_OTP_SCREEN';
export const VERIFY_PAN_SCREEN = 'VERIFY_PAN_SCREEN';
export const VERIFY_BANK_SCREEN = 'VERIFY_BANK_SCREEN';
export const MANAGE_PAYMENTS_SCREEN = 'MANAGE_PAYMENTS_SCREEN';
export const ADD_CARD_SCREEN = 'ADD_CARD_SCREEN';
